site_name: graphql-php
pages:
- About: index.md
- Getting Started: getting-started.md
- Type System:
  - Introduction: type-system/index.md
  - Object Types: type-system/object-types.md
  - Scalar Types: type-system/scalar-types.md
  - Enumeration Types: type-system/enum-types.md
  - Lists and Non-Null: type-system/lists-and-nonnulls.md
  - Interfaces: type-system/interfaces.md
  - Unions: type-system/unions.md
  - Input Types: type-system/input-types.md
  - Defining Schema: type-system/schema.md
  - Custom Metadata: type-system/metadata.md
- Data Fetching: data-fetching.md
- Best Practices: best-practices.md
- Complementary Tools: complementary-tools.md
theme: readthedocs
