site_name: graphql-php
pages:
- About: index.md
- Getting Started: getting-started.md
- Complementary Tools: complementary-tools.md
- Type Definitions:
  - Introduction: type-system/index.md
  - Object Types: type-system/object-types.md
  - Scalar Types: type-system/scalar-types.md
  - Enumeration Types: type-system/enum-types.md
  - Lists and Non-Null: type-system/lists-and-nonnulls.md
  - Interfaces: type-system/interfaces.md
  - Unions: type-system/unions.md
  - Mutations and Input Types: type-system/input-types.md
  - Directives: type-system/directives.md
  - Schema: type-system/schema.md
  - Using Type Language: type-system/type-language.md
- Executing Queries: executing-queries.md
- Fetching Data: data-fetching.md
- Handling Errors: error-handling.md
# - Mutations: mutations.md
- Security: security.md
# - Performance tips: performance.md
- How it works: how-it-works.md
- Class Reference: reference.md
theme: readthedocs
