name: "Format"

on:
  push:

jobs:
  prettify-markdown:
    name: "Prettify markdown"
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          ref: "${{ github.head_ref }}"

      - name: "Run prettier on markdown files"
        uses: "creyD/prettier_action@v2.2"
        with:
          prettier_options: "--write --tab-width=2 *.md **/*.md"
          branch: "${{ github.head_ref }}"
          commit_message: "Prettify markdown"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
